# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Enables namespacing of each library's R class
android.nonTransitiveRClass=true

# Gradle configuration cache / parallel builds
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.java.home=C\:\\Users\\phqua\\AppData\\Local\\Programs\\Eclipse Adoptium\\jdk-17.0.19.10-hotspot
